### PR TITLE
Default -n to 3 and always pass --privileged to agent

### PR DESCRIPTION
**Pull request by ibuildthecloud**
@cloudnautique

### CODE REVIEW

**Comment by cloudnautique** [comment]
Can you update the readme as well.

**Comment by cloudnautique** [comment]
ping @ibuildthecloud

**Comment by ibuildthecloud** [comment]
@cloudnautique Updated.  I did a `./bin/gce-10acre-ranch -h` and just copied the output and put it in the README.md.  Apparently there were other small changes.

**Comment by cloudnautique** [comment]
These should all be addressed now...closing..

**Pull request closed without merging**
